# Generated by Django 4.1.2 on 2022-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mystery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mystery_title", models.CharField(max_length=250)),
                ("mysteryid", models.CharField(max_length=3)),
                ("genre", models.CharField(max_length=15)),
                ("difficulty", models.CharField(max_length=10)),
                ("percentage_solved", models.IntegerField(default=0)),
                ("storyparagraphs", models.CharField(max_length=25500)),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("emailaddress", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
            ],
        ),
    ]
